# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=200)),
                ('Cooler', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cars_lines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=200)),
                ('number_of_Employees', models.IntegerField()),
                ('car_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Cars')),
            ],
        ),
        migrations.CreateModel(
            name='Duties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('go', 'go'), ('back', 'back')], max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('Counter', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Cars')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_problem', models.CharField(max_length=200)),
                ('case', models.CharField(choices=[('nede fix', 'nede fix'), ('fix', 'fix')], max_length=200)),
                ('possibility_of_fix', models.CharField(choices=[('nyes', 'yes'), ('no', 'no'), ('good', 'good')], max_length=200)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Cars')),
            ],
        ),
        migrations.CreateModel(
            name='Names',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='maintenance',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Names'),
        ),
        migrations.AddField(
            model_name='duties',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Names'),
        ),
        migrations.AddField(
            model_name='cars_lines',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Names'),
        ),
    ]
